virtual-host: 127.0.0.1
server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nexus?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 2691386627
    druid:
      initial-size: 5 # 连接池初始化大小
      min-idle: 10 # 最小空闲连接数
      max-active: 20 # 最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: # 访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  data:
    mongodb:
      host: ${virtual-host}
      port: 27017
      database: nexus
    elasticsearch:
      repositories:
        enabled: true
  elasticsearch:
    uris: ${virtual-host}:9200
  rabbitmq:
    host: ${virtual-host}
    port: 5672
    virtual-host: /nexus
    username: nexus
    password: nexus

secure:
  ignored:
    urls: # 安全路径白名单
      - /swagger-ui
      - /swagger-resources/**
      - /system/**
      - /**/v2/api-docs
      - /**/*.html
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.map
      - /auth/**
      - /hello
      - /**

mybatis:
  type-handlers-package: cn.edu.nwafu.nexus.infrastructure.typehandler
